INSERT INTO  ANALYTICS.DBT_AKADLAG.STG_CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME,FIRST_ORDER_DATE,MOST_RECENT_ORDER_DATE,NUMBER_OF_ORDERS)

SELECT CUSTOMER_ID, FIRST_NAME, LAST_NAME,FIRST_ORDER_DATE,MOST_RECENT_ORDER_DATE,NUMBER_OF_ORDERS FROM ANALYTICS.DBT_AKADLAG.STG_CUSTOMERS 