INSERT INTO INSURANCECLAIM.PUBLIC.MEMBERS VALUES(4, 'Aparna', 'Kadlag', 29),(5, 'gauarv', 'kadlag', 30);
select * from INSURANCECLAIM.PUBLIC.MEMBERS


ALTER TABLE INSURANCECLAIM.PUBLIC.MEMBERS
ADD column Colocations STRING;